from django.contrib.gis.db import models
from django.conf import settings

#Used for Geographic Reports

class Cities(models.Model):
    objectid = models.IntegerField()
    fips_code = models.CharField(max_length=5)
    name = models.CharField(max_length=50)
    acres = models.FloatField()
    gis_prc_dt = models.CharField(max_length=10)
    effectv_dt = models.CharField(max_length=15)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="City Boundaries")
    objects = models.GeoManager()
    
class Islands(models.Model):
    objectid = models.IntegerField()
    area = models.FloatField()
    perimeter = models.FloatField()
    org_bnd = models.IntegerField()
    org_bnd_id = models.IntegerField()
    status = models.CharField(max_length=5)
    nwrunit = models.CharField(max_length=3)
    nwrname = models.CharField(max_length=3)
    ifwsno = models.CharField(max_length=5)
    acreage = models.FloatField()
    tractno = models.CharField(max_length=15)
    islandno = models.CharField(max_length=10, null=True, blank=True)
    namenoaa = models.CharField(max_length=50, null=True, blank=True)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Islands")
    objects = models.GeoManager()    
    
class Ports(models.Model):
    objectid = models.IntegerField()
    name = models.CharField(max_length=100)
    county = models.CharField(max_length=35)
    harbor = models.CharField(max_length=5)
    geometry = models.PointField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Oregon Ports")
    objects = models.GeoManager()

class Counties(models.Model):
    objectid_1 = models.IntegerField()
    objectid = models.IntegerField()
    name = models.CharField(max_length=15)
    cobcode = models.CharField(max_length=5)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="County Boundaries")
    objects = models.GeoManager()    
    
class Shoreline(models.Model):
    objectid = models.IntegerField()
    fnode = models.FloatField()
    tnode = models.FloatField()
    lpoly = models.FloatField()
    rpoly = models.FloatField()
    length = models.FloatField()
    esi_line = models.FloatField()
    esi_line_i = models.FloatField()
    fnode_1 = models.FloatField()
    tnode_1 = models.FloatField()
    lpoly_1 = models.FloatField()
    rpoly_1 = models.FloatField()
    esi_field = models.FloatField()
    esi_id = models.FloatField()
    esi = models.CharField(max_length=10)
    line = models.CharField(max_length=1)
    source_id = models.FloatField()
    shape_leng = models.FloatField()
    geometry = models.MultiLineStringField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Shoreline")
    objects = models.GeoManager()    
    
class RockyShores(models.Model):
    objectid = models.IntegerField()
    rsindx = models.IntegerField()
    name = models.CharField(max_length=45)
    desig = models.IntegerField()
    reg = models.FloatField()
    site = models.IntegerField()
    size = models.IntegerField()
    bc = models.IntegerField()
    pc = models.IntegerField()
    it_cl = models.IntegerField()
    bm_cl = models.IntegerField()
    te_species = models.CharField(max_length=12, null=True, blank=True)
    visitor = models.IntegerField()
    ed_u = models.IntegerField()
    com_u = models.IntegerField()
    rec_u = models.IntegerField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Rocky Shores")
    objects = models.GeoManager()    
    
#Used for Physical Reports    
    
class ClosedShoreline(models.Model):
    objectid = models.IntegerField()
    fnode = models.IntegerField()
    tnode = models.IntegerField()
    lpoly = models.IntegerField()
    rpoly = models.IntegerField()
    length = models.FloatField()
    esi_ln = models.IntegerField()
    esi_ln_id = models.IntegerField()
    shape_leng = models.FloatField()
    geometry = models.MultiLineStringField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Closed Shoreline")
    objects = models.GeoManager()    
    
class Lithology(models.Model):
    objectid = models.IntegerField()
    lith_inter = models.CharField(max_length=24)
    lithology = models.CharField(max_length=20)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Territorial Sea Lithology")
    objects = models.GeoManager()
    
#Used for Biological Reports    
    
class PinnipedHaulouts(models.Model):
    objectid = models.IntegerField()
    location = models.CharField(max_length=254)
    site = models.CharField(max_length=254)
    lat = models.FloatField()
    lon = models.FloatField()
    generality = models.FloatField()
    pv_use = models.FloatField()
    ej_use = models.FloatField()
    zc_use = models.FloatField()
    ma_use = models.FloatField()
    pv_count = models.FloatField()
    ej_count = models.FloatField()
    zc_count = models.FloatField()
    ma_count = models.FloatField()
    ej_rookery = models.IntegerField()
    geometry = models.PointField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Pinniped Haulouts")
    objects = models.GeoManager()    
    
class SeabirdColonies(models.Model):
    objectid_1 = models.IntegerField()
    objectid = models.IntegerField()
    colno = models.CharField(max_length=15)
    colno_gis = models.CharField(max_length=10)
    complex = models.CharField(max_length=50)
    site_name = models.CharField(max_length=60)
    date = models.DateField()
    year = models.FloatField()
    dateinterp = models.CharField(max_length=1)
    observers = models.CharField(max_length=50)
    survtype = models.CharField(max_length=10)
    sp = models.CharField(max_length=4)
    species = models.CharField(max_length=40)
    tax_no = models.FloatField()
    actual_bir = models.FloatField()
    nonests = models.FloatField()
    est_no_bre = models.CharField(max_length=10)
    mostrecent = models.CharField(max_length=3)
    whatcount = models.CharField(max_length=3)
    esttype = models.CharField(max_length=3)
    convert = models.CharField(max_length=5)
    reps = models.FloatField()
    qual = models.FloatField()
    dataent = models.DateField(null=True, blank=True)
    datahack = models.CharField(max_length=25)
    biblno = models.FloatField()
    author = models.CharField(max_length=254)
    contact = models.CharField(max_length=100)
    document = models.CharField(max_length=100)
    year_pub = models.FloatField()
    cen_notes = models.CharField(max_length=254, null=True, blank=True)
    spnotes = models.CharField(max_length=254, null=True, blank=True)
    mapno = models.CharField(max_length=50)
    siteno = models.CharField(max_length=15)
    state = models.CharField(max_length=4)
    county = models.CharField(max_length=25)
    country = models.CharField(max_length=15)
    bcregion = models.FloatField()
    desc = models.CharField(max_length=254)
    datapg = models.FloatField()
    photo_inte = models.CharField(max_length=150, null=True, blank=True)
    use = models.CharField(max_length=3)
    title = models.CharField(max_length=120)
    volume = models.CharField(max_length=10, null=True, blank=True)
    issue = models.CharField(max_length=10, null=True, blank=True)
    pages = models.CharField(max_length=15, null=True, blank=True)
    keywords = models.CharField(max_length=254, null=True, blank=True)
    utmx = models.FloatField()
    utmy = models.FloatField()
    cat07_mra = models.IntegerField()
    geometry = models.PointField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Seabird Colonies")
    objects = models.GeoManager()
    
class Habitats(models.Model):
    objectid_1 = models.IntegerField()
    objectid_2 = models.FloatField()
    objectid = models.FloatField()
    structure = models.CharField(max_length=20)
    structure2 = models.CharField(max_length=20, null=True, blank=True)
    geo_hab = models.CharField(max_length=10, null=True, blank=True)
    lithology = models.CharField(max_length=19, null=True, blank=True)
    lithology2 = models.CharField(max_length=20, null=True, blank=True)
    properties = models.CharField(max_length=50, null=True, blank=True)
    gravel = models.FloatField()
    sand = models.FloatField()
    silt = models.FloatField()
    clay = models.FloatField()
    num_sample = models.FloatField()
    sum = models.FloatField()
    f_area = models.FloatField()
    hab_type = models.CharField(max_length=40)
    area = models.FloatField()
    len = models.FloatField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Seafloor Habitats")
    objects = models.GeoManager()    
    
class KelpSurveys(models.Model):
    objectid = models.IntegerField()
    kelp90 = models.IntegerField()
    kelp96 = models.IntegerField()
    kelp97 = models.IntegerField()
    kelp98 = models.IntegerField()
    kelp99 = models.IntegerField()
    area = models.FloatField()
    perimeter = models.FloatField()
    acres = models.FloatField()
    hectares = models.FloatField()
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geometry = models.MultiPolygonField(srid=settings.GEOMETRY_DB_SRID, null=True, blank=True, verbose_name="Kelp Surveys")
    objects = models.GeoManager()    