
port_names = [      'Astoria', 
                    'Garibaldi/Tillamook', 
                    'Depoe Bay', 
                    'Newport', 
                    'Florence', 
                    'SOORC Ports', 
                    'Port Orford', 
                    'Gold Beach & Brookings'  ]
                    
port_abbrs = {      'Astoria': 'astr', 
                    'Garibaldi/Tillamook': 'tllr', 
                    'Depoe Bay': 'dpor', 
                    'Newport': 'newr', 
                    'Florence': 'flrr', 
                    'SOORC Ports': 'srcr', 
                    'Port Orford': 'orfr', 
                    'Gold Beach & Brookings': 'bgdr' }

fisheries = [       ('Dungeness crab - trap', 'dcrabt'),
                    ('Hagfish - trap', 'hagt'), 
                    ('Pacific Halibut - longline', 'phall'), 
                    ('Petrale Sole - trawl', 'psolet'), 
                    ('Pink Shrimp - trawl', 'pshpt'),
                    ('Rockfish - hook & line (dead)', 'rdead'), 
                    ('Rockfish - hook & line (live)', 'rlive'), 
                    ('Rockfish - longline (dead)', 'rdeadl'), 
                    ('Rockfish - longline (live)', 'rlivel'), 
                    ('Sablefish - trap', 'sabt'), 
                    ('Sablefish - longline', 'sabl'), 
                    ('Salmon - troll', 'salt'), 
                    ('Seaward RCA - trawl', 'srcat'), 
                    ('Shelf Bottom - trawl', 'shbt'), 
                    ('Urchin - dive', 'urchd'), 
                    ('Whiting - midwater trawl', 'wmidt')  ]                     

noaa_multipliers = {'dcrabt': 1.95, 
                    'hagt': 1.86, 
                    'phall': 1.86, 
                    'psolet': 1.9,
                    'pshpt': 1.84, 
                    'rdead': 1.90, 
                    'rlive': 1.90, 
                    'rdeadl': 1.90, 
                    'rlivel': 1.90, 
                    'sabl': 1.90, 
                    'sabt': 1.90, 
                    'salt': 1.86, 
                    'srcat': 1.90, 
                    'shbt': 1.86, 
                    'urchd': 1.87, 
                    'wmidt': 1.90  } 
                    
#the following are gleaned from the '110921 FEAM Economic Factors Final.xlsx' doc
feam_multipliers = {'astr':{'dcrabt': 1.5, 
                            'hagt': 1.77, 
                            'phall': 1.45,  
                            'psolet': 1.44,
                            'pshpt': 1.94, 
                            'rdead': 2.28, 
                            'rlive': 1.26, 
                            'rdeadl': 2.28,
                            'rlivel': 1.26,   
                            'sabl': 1.4, 
                            'sabt': 1.4, 
                            'salt': 1.38, 
                            'srcat': 2., 
                            'shbt': 2., 
                            'wmidt': 3.22  },  
                    'tllr':{'dcrabt': 1.24, 
                            'hagt': 1.67, 
                            'phall': 1.28,  
                            'psolet': 1.28,
                            'pshpt': 1.55, 
                            'rdead': 1.23, 
                            'rlive': 1.09, 
                            'rdeadl': 1.23, 
                            'sabl': 1.22, 
                            'sabt': 1.22, 
                            'salt': 1.1, 
                            'srcat': 1.37, 
                            'shbt': 1.37, 
                            'urchd': 1.24 },
                    'dpor':{'dcrabt': 1.44,
                            'phall': 1.37,  
                            'psolet': 1.4,
                            'rdead': 1.55, 
                            'rlive': 1.25,
                            'salt': 1.3,
                            'urchd': 1.24 },
                    'newr':{'dcrabt': 1.44, 
                            'hagt': 1.76, 
                            'phall': 1.37,  
                            'psolet': 1.4,
                            'pshpt': 1.89, 
                            'rdead': 1.55, 
                            'rlive': 1.25, 
                            'rdeadl': 1.55, 
                            'sabl': 1.29, 
                            'sabt': 1.29, 
                            'salt': 1.3, 
                            'srcat': 1.75, 
                            'shbt': 1.75, 
                            'urchd': 1.24, 
                            'wmidt': 3.71 },
                    'flrr':{'dcrabt': 1.23, 
                            'phall': 1.38,  
                            'psolet': 1.27,
                            'sabl': 1.18, 
                            'sabt': 1.18, 
                            'salt': 1.23, 
                            'srcat': 1.4 },
                    'srcr':{'dcrabt': 1.23,
                            'hagt': 1.86, 
                            'phall': 1.38,  
                            'psolet': 1.27,
                            'pshpt': 1.96, 
                            'rdead': 1.29, 
                            'rlive': 1.21, 
                            'rdeadl': 1.29,
                            'rlivel': 1.21, 
                            'sabl': 1.18,  
                            'sabt': 1.18,  
                            'salt': 1.23,  
                            'srcat': 1.4, 
                            'shbt': 1.41, 
                            'urchd': 1.22, 
                            'wmidt': 4.21  },
                    'orfr':{'dcrabt': 1.12, 
                            'hagt': 1.73, 
                            'phall': 1.14,  
                            'psolet': 1.13,
                            'rdead': 1.18, 
                            'rlive': 1.12, 
                            'rdeadl': 1.18, 
                            'rlivel': 1.12, 
                            'sabl': 1.13, 
                            'sabt': 1.13, 
                            'salt': 1.09,
                            'urchd': .94 },
                    'bgdr':{'dcrabt': 1.12, 
                            'phall': 1.14,  
                            'psolet': 1.13,
                            'pshpt': 1.18, 
                            'rdead': 1.18,   
                            'rlive': 1.12,  
                            'rdeadl': 1.18,  
                            'rlivel': 1.12, 
                            'sabl': 1.13,    
                            'sabt': 1.13,   
                            'salt': 1.09,    
                            'srcat': 1.23, 
                            'shbt': 1.23, 
                            'urchd': .94 },
                    'statewide':
                           {'dcrabt': 1.75, 
                            'hagt': 2.17, 
                            'phall': 1.61,  
                            'psolet': 1.74,
                            'pshpt': 2.32, 
                            'rdead': 1.94, 
                            'rlive': 1.47, 
                            'rdeadl': 1.94, 
                            'rlivel': 1.47,
                            'sabl': 1.59, 
                            'sabt': 1.59, 
                            'salt': 1.53, 
                            'srcat': 2.26, 
                            'shbt': 2.26, 
                            'urchd': 1.55, 
                            'wmidt': 4.42 },
                    }

commercial_totals = {   'astr':{'dcrabt': 7803273.51, 
                                'phall': 240514.17,  
                                'psolet': 1019636.55,
                                'pshpt': 2117303.96, 
                                'rdead': 1.0,   
                                'sabl': 292140.01,
                                'salt': 432984.05, 
                                'srcat': 4858352.51, 
                                'shbt': 1565374.47, 
                                'wmidt': 2540368.81  },  
                        'tllr':{'dcrabt': 2503184.16, 
                                'phall': 7498.96, 
                                'pshpt': 416932.52, 
                                'rdead': 52841.27, 
                                'rlive': 10156.27, 
                                'sabl': 4853.31, 
                                'salt': 414845.10, 
                                'srcat': 5812.55, 
                                'shbt': 1927.38 },
                        'dpor':{'dcrabt': 81938.86,
                                'rdead': 4493.61, 
                                'rlive': 3257.67,
                                'salt': 12381.67,
                                'urchd': 33837.58 },
                        'newr':{'dcrabt': 13357016.97, 
                                'hagt': 80268.54, 
                                'phall': 405870.93,  
                                'psolet': 274076.31,
                                'pshpt': 3064362.61, 
                                'rdead': 23673.39, 
                                'rlive': 978.56, 
                                'sabl': 982122.35, 
                                'sabt': 991000.16, 
                                'salt': 1957953.23, 
                                'srcat': 2618846.29, 
                                'shbt': 265365.55, 
                                'wmidt': 3986363.56 },
                        'flrr':{'dcrabt': 85112.49, 
                                'phall': 2076.52, 
                                'sabl': 618.78, 
                                'sabt': 110.60, 
                                'salt': 29495.27, 
                                'srcat': 3499.87 },
                        'srcr':{'dcrabt': 10764800.93,
                                'hagt': 358067.60, 
                                'phall': 208631.66,  
                                'psolet': 626028.21,
                                'pshpt': 2421916.54, 
                                'rdead': 22794.23, 
                                'rlive': 1219.61, 
                                'rdeadl': 4024.14,
                                'sabl': 568748.04,  
                                'sabt': 677825.96,  
                                'salt': 1964161.80,  
                                'srcat': 2878060.24, 
                                'shbt': 152842.49, 
                                'urchd': 24757.54, 
                                'wmidt': 534481.47  },
                        'orfr':{'dcrabt': 1882081.78, 
                                'hagt': 7561.16, 
                                'phall': 21862.69, 
                                'rdead': 14721.21, 
                                'rlive': 376941.16, 
                                'rdeadl': 3848.49, 
                                'rlivel': 79041.99, 
                                'sabl': 829092.59, 
                                'salt': 305748.42,
                                'urchd': 88124.73 },
                        'bgdr':{'dcrabt': 4412997.53, 
                                'psolet': 106197.80,
                                'pshpt': 275339.19, 
                                'rdead': 37887.19,   
                                'rlive': 333853.15,  
                                'rdeadl': 189.89, 
                                'sabl': 61472.54,    
                                'sabt': 17313.39,   
                                'salt': 238392.10,    
                                'srcat': 1085026.17, 
                                'urchd': 24746.02 },
                        'state':
                               {'dcrabt': 40890406.23, 
                                'hagt': 445897.30, 
                                'phall': 886454.94,  
                                'psolet': 2025938.86,
                                'pshpt': 8295854.83, 
                                'rdead': 156410.91, 
                                'rlive': 726406.42, 
                                'rdeadl': 8062.52, 
                                'rlivel': 79041.99,
                                'sabl': 2739047.62, 
                                'sabt': 1686250.11, 
                                'salt': 5355961.63, 
                                'srcat': 11449597.63, 
                                'shbt': 1985509.89, 
                                'urchd': 171465.86, 
                                'wmidt': 7061213.84 },
                }                                      
                    