# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):
    
    def forwards(self, orm):
        
        # Adding model 'KelpSurveys'
        db.create_table('analysis_kelpsurveys', (
            ('perimeter', self.gf('django.db.models.fields.FloatField')()),
            ('shape_area', self.gf('django.db.models.fields.FloatField')()),
            ('kelp99', self.gf('django.db.models.fields.IntegerField')()),
            ('kelp98', self.gf('django.db.models.fields.IntegerField')()),
            ('objectid', self.gf('django.db.models.fields.IntegerField')()),
            ('area', self.gf('django.db.models.fields.FloatField')()),
            ('geometry', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=99999, null=True, blank=True)),
            ('kelp97', self.gf('django.db.models.fields.IntegerField')()),
            ('kelp96', self.gf('django.db.models.fields.IntegerField')()),
            ('kelp90', self.gf('django.db.models.fields.IntegerField')()),
            ('acres', self.gf('django.db.models.fields.FloatField')()),
            ('hectares', self.gf('django.db.models.fields.FloatField')()),
            ('shape_leng', self.gf('django.db.models.fields.FloatField')()),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
        ))
        db.send_create_signal('analysis', ['KelpSurveys'])

        # Adding model 'PinnipedHaulouts'
        db.create_table('analysis_pinnipedhaulouts', (
            ('ej_rookery', self.gf('django.db.models.fields.IntegerField')()),
            ('generality', self.gf('django.db.models.fields.FloatField')()),
            ('objectid', self.gf('django.db.models.fields.IntegerField')()),
            ('ma_use', self.gf('django.db.models.fields.FloatField')()),
            ('pv_use', self.gf('django.db.models.fields.FloatField')()),
            ('lon', self.gf('django.db.models.fields.FloatField')()),
            ('site', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('zc_use', self.gf('django.db.models.fields.FloatField')()),
            ('geometry', self.gf('django.contrib.gis.db.models.fields.PointField')(srid=99999, null=True, blank=True)),
            ('pv_count', self.gf('django.db.models.fields.FloatField')()),
            ('location', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('ej_count', self.gf('django.db.models.fields.FloatField')()),
            ('ej_use', self.gf('django.db.models.fields.FloatField')()),
            ('lat', self.gf('django.db.models.fields.FloatField')()),
            ('ma_count', self.gf('django.db.models.fields.FloatField')()),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('zc_count', self.gf('django.db.models.fields.FloatField')()),
        ))
        db.send_create_signal('analysis', ['PinnipedHaulouts'])

        # Adding model 'SeabirdColonies'
        db.create_table('analysis_seabirdcolonies', (
            ('tax_no', self.gf('django.db.models.fields.FloatField')()),
            ('site_name', self.gf('django.db.models.fields.CharField')(max_length=60)),
            ('objectid', self.gf('django.db.models.fields.IntegerField')()),
            ('dataent', self.gf('django.db.models.fields.DateField')()),
            ('datapg', self.gf('django.db.models.fields.FloatField')()),
            ('year_pub', self.gf('django.db.models.fields.FloatField')()),
            ('county', self.gf('django.db.models.fields.CharField')(max_length=25)),
            ('mapno', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('survtype', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('biblno', self.gf('django.db.models.fields.FloatField')()),
            ('year', self.gf('django.db.models.fields.FloatField')()),
            ('keywords', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('desc', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('species', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('use', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('objectid_1', self.gf('django.db.models.fields.IntegerField')()),
            ('author', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('cat07_mra', self.gf('django.db.models.fields.IntegerField')()),
            ('actual_bir', self.gf('django.db.models.fields.FloatField')()),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=4)),
            ('complex', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('siteno', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('utmx', self.gf('django.db.models.fields.FloatField')()),
            ('utmy', self.gf('django.db.models.fields.FloatField')()),
            ('document', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('issue', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('photo_inte', self.gf('django.db.models.fields.CharField')(max_length=150)),
            ('datahack', self.gf('django.db.models.fields.CharField')(max_length=25)),
            ('bcregion', self.gf('django.db.models.fields.FloatField')()),
            ('title', self.gf('django.db.models.fields.CharField')(max_length=120)),
            ('reps', self.gf('django.db.models.fields.FloatField')()),
            ('spnotes', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('observers', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('nonests', self.gf('django.db.models.fields.FloatField')()),
            ('dateinterp', self.gf('django.db.models.fields.CharField')(max_length=1)),
            ('colno', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('date', self.gf('django.db.models.fields.DateField')()),
            ('whatcount', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('pages', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('esttype', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('volume', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('convert', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('qual', self.gf('django.db.models.fields.FloatField')()),
            ('est_no_bre', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('sp', self.gf('django.db.models.fields.CharField')(max_length=4)),
            ('mostrecent', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('geometry', self.gf('django.contrib.gis.db.models.fields.PointField')(srid=99999, null=True, blank=True)),
            ('contact', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('colno_gis', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('cen_notes', self.gf('django.db.models.fields.CharField')(max_length=254)),
        ))
        db.send_create_signal('analysis', ['SeabirdColonies'])

        # Adding model 'Habitats'
        db.create_table('analysis_habitats', (
            ('hab_type', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('objectid', self.gf('django.db.models.fields.FloatField')()),
            ('lithology2', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('shape_leng', self.gf('django.db.models.fields.FloatField')()),
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('objectid_1', self.gf('django.db.models.fields.IntegerField')()),
            ('objectid_2', self.gf('django.db.models.fields.FloatField')()),
            ('sum', self.gf('django.db.models.fields.FloatField')()),
            ('gravel', self.gf('django.db.models.fields.FloatField')()),
            ('silt', self.gf('django.db.models.fields.FloatField')()),
            ('lithology', self.gf('django.db.models.fields.CharField')(max_length=19)),
            ('f_area', self.gf('django.db.models.fields.FloatField')()),
            ('len', self.gf('django.db.models.fields.FloatField')()),
            ('num_sample', self.gf('django.db.models.fields.FloatField')()),
            ('geo_hab', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('properties', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('structure', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('shape_area', self.gf('django.db.models.fields.FloatField')()),
            ('geometry', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=99999, null=True, blank=True)),
            ('area', self.gf('django.db.models.fields.FloatField')()),
            ('sand', self.gf('django.db.models.fields.FloatField')()),
            ('clay', self.gf('django.db.models.fields.FloatField')()),
            ('structure2', self.gf('django.db.models.fields.CharField')(max_length=20)),
        ))
        db.send_create_signal('analysis', ['Habitats'])
    
    
    def backwards(self, orm):
        
        # Deleting model 'KelpSurveys'
        db.delete_table('analysis_kelpsurveys')

        # Deleting model 'PinnipedHaulouts'
        db.delete_table('analysis_pinnipedhaulouts')

        # Deleting model 'SeabirdColonies'
        db.delete_table('analysis_seabirdcolonies')

        # Deleting model 'Habitats'
        db.delete_table('analysis_habitats')
    
    
    models = {
        'analysis.cities': {
            'Meta': {'object_name': 'Cities'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'effectv_dt': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'fips_code': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'gis_prc_dt': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.closedshoreline': {
            'Meta': {'object_name': 'ClosedShoreline'},
            'esi_ln': ('django.db.models.fields.IntegerField', [], {}),
            'esi_ln_id': ('django.db.models.fields.IntegerField', [], {}),
            'fnode': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'lpoly': ('django.db.models.fields.IntegerField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'rpoly': ('django.db.models.fields.IntegerField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'tnode': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.counties': {
            'Meta': {'object_name': 'Counties'},
            'cobcode': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.habitats': {
            'Meta': {'object_name': 'Habitats'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'clay': ('django.db.models.fields.FloatField', [], {}),
            'f_area': ('django.db.models.fields.FloatField', [], {}),
            'geo_hab': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'gravel': ('django.db.models.fields.FloatField', [], {}),
            'hab_type': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'len': ('django.db.models.fields.FloatField', [], {}),
            'lithology': ('django.db.models.fields.CharField', [], {'max_length': '19'}),
            'lithology2': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'num_sample': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.FloatField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_2': ('django.db.models.fields.FloatField', [], {}),
            'properties': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'sand': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'silt': ('django.db.models.fields.FloatField', [], {}),
            'structure': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'structure2': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'sum': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.islands': {
            'Meta': {'object_name': 'Islands'},
            'acreage': ('django.db.models.fields.FloatField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ifwsno': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'islandno': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'namenoaa': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'nwrname': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'nwrunit': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'org_bnd': ('django.db.models.fields.IntegerField', [], {}),
            'org_bnd_id': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'tractno': ('django.db.models.fields.CharField', [], {'max_length': '15'})
        },
        'analysis.kelpsurveys': {
            'Meta': {'object_name': 'KelpSurveys'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'hectares': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'kelp90': ('django.db.models.fields.IntegerField', [], {}),
            'kelp96': ('django.db.models.fields.IntegerField', [], {}),
            'kelp97': ('django.db.models.fields.IntegerField', [], {}),
            'kelp98': ('django.db.models.fields.IntegerField', [], {}),
            'kelp99': ('django.db.models.fields.IntegerField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.lithology': {
            'Meta': {'object_name': 'Lithology'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lith_inter': ('django.db.models.fields.CharField', [], {'max_length': '24'}),
            'lithology': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.pinnipedhaulouts': {
            'Meta': {'object_name': 'PinnipedHaulouts'},
            'ej_count': ('django.db.models.fields.FloatField', [], {}),
            'ej_rookery': ('django.db.models.fields.IntegerField', [], {}),
            'ej_use': ('django.db.models.fields.FloatField', [], {}),
            'generality': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lat': ('django.db.models.fields.FloatField', [], {}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'lon': ('django.db.models.fields.FloatField', [], {}),
            'ma_count': ('django.db.models.fields.FloatField', [], {}),
            'ma_use': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'pv_count': ('django.db.models.fields.FloatField', [], {}),
            'pv_use': ('django.db.models.fields.FloatField', [], {}),
            'site': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'zc_count': ('django.db.models.fields.FloatField', [], {}),
            'zc_use': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.ports': {
            'Meta': {'object_name': 'Ports'},
            'county': ('django.db.models.fields.CharField', [], {'max_length': '35'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'harbor': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.rockyshores': {
            'Meta': {'object_name': 'RockyShores'},
            'bc': ('django.db.models.fields.IntegerField', [], {}),
            'bm_cl': ('django.db.models.fields.IntegerField', [], {}),
            'com_u': ('django.db.models.fields.IntegerField', [], {}),
            'desig': ('django.db.models.fields.IntegerField', [], {}),
            'ed_u': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'it_cl': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '45'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'pc': ('django.db.models.fields.IntegerField', [], {}),
            'rec_u': ('django.db.models.fields.IntegerField', [], {}),
            'reg': ('django.db.models.fields.FloatField', [], {}),
            'rsindx': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'site': ('django.db.models.fields.IntegerField', [], {}),
            'size': ('django.db.models.fields.IntegerField', [], {}),
            'te_species': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'visitor': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.seabirdcolonies': {
            'Meta': {'object_name': 'SeabirdColonies'},
            'actual_bir': ('django.db.models.fields.FloatField', [], {}),
            'author': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'bcregion': ('django.db.models.fields.FloatField', [], {}),
            'biblno': ('django.db.models.fields.FloatField', [], {}),
            'cat07_mra': ('django.db.models.fields.IntegerField', [], {}),
            'cen_notes': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'colno': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'colno_gis': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'complex': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'contact': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'convert': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'dataent': ('django.db.models.fields.DateField', [], {}),
            'datahack': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'datapg': ('django.db.models.fields.FloatField', [], {}),
            'date': ('django.db.models.fields.DateField', [], {}),
            'dateinterp': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'desc': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'document': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'est_no_bre': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'esttype': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'issue': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'keywords': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'mapno': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'mostrecent': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'nonests': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'observers': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'pages': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'photo_inte': ('django.db.models.fields.CharField', [], {'max_length': '150'}),
            'qual': ('django.db.models.fields.FloatField', [], {}),
            'reps': ('django.db.models.fields.FloatField', [], {}),
            'site_name': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'siteno': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'sp': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'species': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'spnotes': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'survtype': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'tax_no': ('django.db.models.fields.FloatField', [], {}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'use': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'utmx': ('django.db.models.fields.FloatField', [], {}),
            'utmy': ('django.db.models.fields.FloatField', [], {}),
            'volume': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'whatcount': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'year': ('django.db.models.fields.FloatField', [], {}),
            'year_pub': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.shoreline': {
            'Meta': {'object_name': 'Shoreline'},
            'esi': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'esi_field': ('django.db.models.fields.FloatField', [], {}),
            'esi_id': ('django.db.models.fields.FloatField', [], {}),
            'esi_line': ('django.db.models.fields.FloatField', [], {}),
            'esi_line_i': ('django.db.models.fields.FloatField', [], {}),
            'fnode': ('django.db.models.fields.FloatField', [], {}),
            'fnode_1': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'line': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'lpoly': ('django.db.models.fields.FloatField', [], {}),
            'lpoly_1': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'rpoly': ('django.db.models.fields.FloatField', [], {}),
            'rpoly_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'source_id': ('django.db.models.fields.FloatField', [], {}),
            'tnode': ('django.db.models.fields.FloatField', [], {}),
            'tnode_1': ('django.db.models.fields.FloatField', [], {})
        }
    }
    
    complete_apps = ['analysis']
