# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'EconCache'
        db.create_table('analysis_econcache', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('type', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('context', self.gf('picklefield.fields.PickledObjectField')()),
            ('wkt_hash', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('analysis', ['EconCache'])


    def backwards(self, orm):
        
        # Deleting model 'EconCache'
        db.delete_table('analysis_econcache')


    models = {
        'analysis.aescache': {
            'Meta': {'object_name': 'AESCache'},
            'context': ('picklefield.fields.PickledObjectField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'wkt_hash': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        'analysis.airports': {
            'Meta': {'object_name': 'Airports'},
            'act_date': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'aero_chart': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'air_taxi': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'cbd_dir': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'cbd_dist': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'cert_type': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'city_name': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'cntl_twr': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'comm_serv': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'county_nam': ('django.db.models.fields.CharField', [], {'max_length': '21'}),
            'county_st': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'cust_lndg': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'cy_08_enp': ('django.db.models.fields.FloatField', [], {}),
            'eff_date': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'elev': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'faa_distri': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'faa_region': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'faa_st': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'fac_cystzp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'null': 'True', 'blank': 'True'}),
            'fac_use': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'fed_agree': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'fullname': ('django.db.models.fields.CharField', [], {'max_length': '42'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'helicopter': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'internatio': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'itin_ops': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'jet_en_ga': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'joint_use': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'lan_fa_ty': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'latitude': ('django.db.models.fields.FloatField', [], {}),
            'local_ops': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'locid': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'longitude': ('django.db.models.fields.FloatField', [], {}),
            'm_eng_ga': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'mil_int': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'mil_lndg_r': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'mil_ops': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'oper_glide': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'oper_mil': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'owner_type': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            's_eng_ga': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'site_no': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'st_postal': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'state_name': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'stfips': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'ultralight': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        'analysis.bathymetry': {
            'Meta': {'object_name': 'Bathymetry'},
            'depth': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'analysis.beacons': {
            'Meta': {'object_name': 'Beacons'},
            'bcnshp': ('django.db.models.fields.IntegerField', [], {}),
            'beacon_typ': ('django.db.models.fields.IntegerField', [], {}),
            'catcam': ('django.db.models.fields.IntegerField', [], {}),
            'catlam': ('django.db.models.fields.IntegerField', [], {}),
            'catspm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colour': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colpat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'condtn': ('django.db.models.fields.IntegerField', [], {}),
            'conrad': ('django.db.models.fields.IntegerField', [], {}),
            'convis': ('django.db.models.fields.IntegerField', [], {}),
            'datend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'datsta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'elevat': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'grup': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'height': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_name': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'inform': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'lnam': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'marsys': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'natcon': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ninfom': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'nobjnm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ntxtds': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'perend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'persta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'picrep': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recdat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recind': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ruin': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'rver': ('django.db.models.fields.IntegerField', [], {}),
            'scamax': ('django.db.models.fields.IntegerField', [], {}),
            'scamin': ('django.db.models.fields.IntegerField', [], {}),
            'sordat': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'sorind': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'txtdsc': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'veracc': ('django.db.models.fields.FloatField', [], {}),
            'verdat': ('django.db.models.fields.IntegerField', [], {}),
            'verlen': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.buoys': {
            'Meta': {'object_name': 'Buoys'},
            'boyshp': ('django.db.models.fields.IntegerField', [], {}),
            'buoy_type': ('django.db.models.fields.IntegerField', [], {}),
            'catcam': ('django.db.models.fields.IntegerField', [], {}),
            'catinb': ('django.db.models.fields.IntegerField', [], {}),
            'catlam': ('django.db.models.fields.IntegerField', [], {}),
            'catspm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colour': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'colpat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'conrad': ('django.db.models.fields.IntegerField', [], {}),
            'datend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'datsta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'grup': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_name': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'inform': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'lnam': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'marsys': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'natcon': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ninfom': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'nobjnm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ntxtds': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'perend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'persta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'picrep': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'prodct': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recdat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recind': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ruin': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'rver': ('django.db.models.fields.IntegerField', [], {}),
            'scamax': ('django.db.models.fields.IntegerField', [], {}),
            'scamin': ('django.db.models.fields.IntegerField', [], {}),
            'sordat': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'sorind': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'txtdsc': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'veracc': ('django.db.models.fields.FloatField', [], {}),
            'verlen': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.cities': {
            'Meta': {'object_name': 'Cities'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'effectv_dt': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'fips_code': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'gis_prc_dt': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.closedshoreline': {
            'Meta': {'object_name': 'ClosedShoreline'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'new_cl_esi': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.coho': {
            'Meta': {'object_name': 'Coho'},
            'comments': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True', 'blank': 'True'}),
            'dist': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'f_exclude': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'f_rch_rate': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'huc4': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'huc5': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'llid': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'p_exclude': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'p_rch_rate': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'reference': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'rev_date': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'sppcode': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'strm_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'subbasin': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'use': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'watershed': ('django.db.models.fields.CharField', [], {'max_length': '80'})
        },
        'analysis.conservationareas': {
            'Meta': {'object_name': 'ConservationAreas'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'prohibit': ('django.db.models.fields.CharField', [], {'max_length': '65', 'null': 'True', 'blank': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'})
        },
        'analysis.counties': {
            'Meta': {'object_name': 'Counties'},
            'cobcode': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.dmdsites': {
            'Meta': {'object_name': 'DMDSites'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'river': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'use': ('django.db.models.fields.CharField', [], {'max_length': '25'})
        },
        'analysis.econcache': {
            'Meta': {'object_name': 'EconCache'},
            'context': ('picklefield.fields.PickledObjectField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'wkt_hash': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        'analysis.fisheryclosures': {
            'Meta': {'object_name': 'FisheryClosures'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.geologicalhabitat': {
            'Meta': {'object_name': 'GeologicalHabitat'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geo_hab': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'geo_hab2': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'len': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.FloatField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_2': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v31': ('django.db.models.fields.FloatField', [], {}),
            'or_sgh_v3_field': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v_1': ('django.db.models.fields.FloatField', [], {}),
            'or_sgh_v_2': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v_3': ('django.db.models.fields.IntegerField', [], {}),
            'orsghg3rp1': ('django.db.models.fields.IntegerField', [], {}),
            'orsghg3rp_field': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'poly_field': ('django.db.models.fields.IntegerField', [], {}),
            'properties': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'rings_nok': ('django.db.models.fields.IntegerField', [], {}),
            'rings_ok': ('django.db.models.fields.IntegerField', [], {}),
            'sgh_combo': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'sgh_lith': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'sgh_lith1': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'sgh_lith2': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'sgh_prefix': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_2': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'structure': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'structure2': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'subclass': ('django.db.models.fields.CharField', [], {'max_length': '13', 'null': 'True', 'blank': 'True'}),
            'subclass_field': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.habitats': {
            'Meta': {'object_name': 'Habitats'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geo_hab': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'geo_hab2': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'len': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.FloatField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_2': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v31': ('django.db.models.fields.FloatField', [], {}),
            'or_sgh_v3_field': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v_1': ('django.db.models.fields.FloatField', [], {}),
            'or_sgh_v_2': ('django.db.models.fields.IntegerField', [], {}),
            'or_sgh_v_3': ('django.db.models.fields.IntegerField', [], {}),
            'orsghg3rp1': ('django.db.models.fields.IntegerField', [], {}),
            'orsghg3rp_field': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'poly_field': ('django.db.models.fields.IntegerField', [], {}),
            'properties': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'rings_nok': ('django.db.models.fields.IntegerField', [], {}),
            'rings_ok': ('django.db.models.fields.IntegerField', [], {}),
            'sgh_combo': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'sgh_lith': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'sgh_lith1': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'sgh_lith2': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'sgh_prefix': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_2': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'structure': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'structure2': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'subclass': ('django.db.models.fields.CharField', [], {'max_length': '13', 'null': 'True', 'blank': 'True'}),
            'subclass_field': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.islands': {
            'Meta': {'object_name': 'Islands'},
            'acreage': ('django.db.models.fields.FloatField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ifwsno': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'islandno': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'namenoaa': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'nwrname': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'nwrunit': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'org_bnd': ('django.db.models.fields.IntegerField', [], {}),
            'org_bnd_id': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'tractno': ('django.db.models.fields.CharField', [], {'max_length': '15'})
        },
        'analysis.kelpsurveys': {
            'Meta': {'object_name': 'KelpSurveys'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'hectares': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'kelp90': ('django.db.models.fields.IntegerField', [], {}),
            'kelp96': ('django.db.models.fields.IntegerField', [], {}),
            'kelp97': ('django.db.models.fields.IntegerField', [], {}),
            'kelp98': ('django.db.models.fields.IntegerField', [], {}),
            'kelp99': ('django.db.models.fields.IntegerField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.lithology': {
            'Meta': {'object_name': 'Lithology'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lith_inter': ('django.db.models.fields.CharField', [], {'max_length': '24'}),
            'lithology': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.marbledmurrelet': {
            'Meta': {'object_name': 'MarbledMurrelet'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'chu': ('django.db.models.fields.IntegerField', [], {}),
            'chu_name': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mmch_fin_1': ('django.db.models.fields.IntegerField', [], {}),
            'mmch_final': ('django.db.models.fields.IntegerField', [], {}),
            'owner_code': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'})
        },
        'analysis.marinas': {
            'Meta': {'object_name': 'Marinas'},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '53', 'null': 'True', 'blank': 'True'}),
            'bank': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'cngdst': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'commodity1': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'commodity2': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'commodity3': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'commodity4': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '17'}),
            'countyfips': ('django.db.models.fields.CharField', [], {'max_length': '13', 'null': 'True', 'blank': 'True'}),
            'datum': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'depth1': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'depth1a': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'depth2': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'depth2a': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'depth3': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'depth3a': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'dockcd': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '22', 'null': 'True', 'blank': 'True'}),
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '21', 'null': 'True', 'blank': 'True'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lastname': ('django.db.models.fields.CharField', [], {'max_length': '33', 'null': 'True', 'blank': 'True'}),
            'latdec': ('django.db.models.fields.FloatField', [], {}),
            'loc_cd': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'long_dec': ('django.db.models.fields.FloatField', [], {}),
            'mapno': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'mile': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '109'}),
            'ndccode': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'oldpwd': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'operator1': ('django.db.models.fields.CharField', [], {'max_length': '160'}),
            'owner': ('django.db.models.fields.CharField', [], {'max_length': '113', 'null': 'True', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '24', 'null': 'True', 'blank': 'True'}),
            'port_name': ('django.db.models.fields.CharField', [], {'max_length': '61'}),
            'portseries': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'purpose': ('django.db.models.fields.CharField', [], {'max_length': '247'}),
            'pwdno': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'remarks': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'rwy_conn': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'seqno': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'stfips': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'totberth1': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'totberth2': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'totberth3': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'town': ('django.db.models.fields.CharField', [], {'max_length': '24'}),
            'version': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'waterway': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'year': ('django.db.models.fields.CharField', [], {'max_length': '6'})
        },
        'analysis.marinemanagedareas': {
            'Meta': {'object_name': 'MarineManagedAreas'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '75'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.nshcache': {
            'Meta': {'object_name': 'NSHCache'},
            'context': ('picklefield.fields.PickledObjectField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'wkt_hash': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        'analysis.outfalls': {
            'Meta': {'object_name': 'Outfalls'},
            'category': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '14'}),
            'class_field': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'epa_number': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'fac_type': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'facility_i': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lat': ('django.db.models.fields.FloatField', [], {}),
            'legal_name': ('django.db.models.fields.CharField', [], {'max_length': '71'}),
            'long': ('django.db.models.fields.FloatField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '70'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'perm_descr': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'permit_no': ('django.db.models.fields.IntegerField', [], {}),
            'permit_typ': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'sic_code': ('django.db.models.fields.IntegerField', [], {}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '4'})
        },
        'analysis.pinnipedhaulouts': {
            'Meta': {'object_name': 'PinnipedHaulouts'},
            'ej_count': ('django.db.models.fields.FloatField', [], {}),
            'ej_rookery': ('django.db.models.fields.IntegerField', [], {}),
            'ej_use': ('django.db.models.fields.FloatField', [], {}),
            'generality': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lat': ('django.db.models.fields.FloatField', [], {}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'lon': ('django.db.models.fields.FloatField', [], {}),
            'ma_count': ('django.db.models.fields.FloatField', [], {}),
            'ma_use': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'pv_count': ('django.db.models.fields.FloatField', [], {}),
            'pv_use': ('django.db.models.fields.FloatField', [], {}),
            'site': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'zc_count': ('django.db.models.fields.FloatField', [], {}),
            'zc_use': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.ports': {
            'Meta': {'object_name': 'Ports'},
            'county': ('django.db.models.fields.CharField', [], {'max_length': '35'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'harbor': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.protectedareas': {
            'Meta': {'object_name': 'ProtectedAreas'},
            'agency': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'hectares': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'lua': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'map_label': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'ownclas': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'prot_area': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'section': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'site_name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'analysis.publicaccess': {
            'Meta': {'object_name': 'PublicAccess'},
            'addr': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'bay': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'benken1': ('django.db.models.fields.IntegerField', [], {}),
            'bike': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'bluff': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'boat': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'boating': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'bridge': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'camping': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'char': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'chtype': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '55'}),
            'comments': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'dat1': ('django.db.models.fields.FloatField', [], {}),
            'dat1_id': ('django.db.models.fields.FloatField', [], {}),
            'dock': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'dune': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'fees': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'forest': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'handi': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'hiking': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'horse': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'jetty': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'kiosk': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'lake': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'lat': ('django.db.models.fields.FloatField', [], {}),
            'locpln': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'lon': ('django.db.models.fields.FloatField', [], {}),
            'lthouse': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'map': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'marina': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'mgmt': ('django.db.models.fields.CharField', [], {'max_length': '55'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '31'}),
            'numpk': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'offshore': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'orv': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'owner': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'parking': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'pathbch': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'ped': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'photoid': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'photos': ('django.db.models.fields.IntegerField', [], {}),
            'prop': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'ramp': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'range': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'rdendtp': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'restrm': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'river': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'rockhead': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'rocktide': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'section': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'shower': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'siteid': ('django.db.models.fields.FloatField', [], {}),
            'stairs': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'surf': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'tabben': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'taxlot': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'tidepl': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'town': ('django.db.models.fields.CharField', [], {'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'trail': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'typeacc': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'veh': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'visual': ('django.db.models.fields.CharField', [], {'max_length': '7', 'null': 'True', 'blank': 'True'}),
            'water': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'waterfrt': ('django.db.models.fields.CharField', [], {'max_length': '11'}),
            'wetland': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'whale': ('django.db.models.fields.CharField', [], {'max_length': '7'})
        },
        'analysis.railroads': {
            'Meta': {'object_name': 'Railroads'},
            'cntyfips': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'den07code': ('django.db.models.fields.IntegerField', [], {}),
            'fraarcid': ('django.db.models.fields.IntegerField', [], {}),
            'fraregion': ('django.db.models.fields.IntegerField', [], {}),
            'frfranode': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'miles': ('django.db.models.fields.FloatField', [], {}),
            'net': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'passngr': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'rrowner1': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'rrowner2': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'rrowner3': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'sigsys': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'stateab': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'statefips': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'stcntyfips': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'stracnet': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'subdiv': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'tofranode': ('django.db.models.fields.IntegerField', [], {}),
            'tracks': ('django.db.models.fields.IntegerField', [], {}),
            'trkrghts1': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts2': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts3': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts4': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts5': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts6': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts7': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts8': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'trkrghts9': ('django.db.models.fields.CharField', [], {'max_length': '4', 'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'yards': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'})
        },
        'analysis.rockyshores': {
            'Meta': {'object_name': 'RockyShores'},
            'bc': ('django.db.models.fields.IntegerField', [], {}),
            'bm_cl': ('django.db.models.fields.IntegerField', [], {}),
            'com_u': ('django.db.models.fields.IntegerField', [], {}),
            'desig': ('django.db.models.fields.IntegerField', [], {}),
            'ed_u': ('django.db.models.fields.IntegerField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'it_cl': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '45'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'pc': ('django.db.models.fields.IntegerField', [], {}),
            'rec_u': ('django.db.models.fields.IntegerField', [], {}),
            'reg': ('django.db.models.fields.FloatField', [], {}),
            'rsindx': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'site': ('django.db.models.fields.IntegerField', [], {}),
            'size': ('django.db.models.fields.IntegerField', [], {}),
            'te_species': ('django.db.models.fields.CharField', [], {'max_length': '12', 'null': 'True', 'blank': 'True'}),
            'visitor': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.seabirdcolonies': {
            'Meta': {'object_name': 'SeabirdColonies'},
            'actual_bir': ('django.db.models.fields.FloatField', [], {}),
            'author': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'bcregion': ('django.db.models.fields.FloatField', [], {}),
            'biblno': ('django.db.models.fields.FloatField', [], {}),
            'cat07_mra': ('django.db.models.fields.IntegerField', [], {}),
            'cen_notes': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colno': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'colno_gis': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'complex': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'contact': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'convert': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'dataent': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'datahack': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'datapg': ('django.db.models.fields.FloatField', [], {}),
            'date': ('django.db.models.fields.DateField', [], {}),
            'dateinterp': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'desc': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'document': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'est_no_bre': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'esttype': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'issue': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'keywords': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'mapno': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'mostrecent': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'nonests': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'objectid_1': ('django.db.models.fields.IntegerField', [], {}),
            'observers': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'pages': ('django.db.models.fields.CharField', [], {'max_length': '15', 'null': 'True', 'blank': 'True'}),
            'photo_inte': ('django.db.models.fields.CharField', [], {'max_length': '150', 'null': 'True', 'blank': 'True'}),
            'qual': ('django.db.models.fields.FloatField', [], {}),
            'reps': ('django.db.models.fields.FloatField', [], {}),
            'site_name': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'siteno': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'sp': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'species': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'spnotes': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'survtype': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'tax_no': ('django.db.models.fields.FloatField', [], {}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'use': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'utmx': ('django.db.models.fields.FloatField', [], {}),
            'utmy': ('django.db.models.fields.FloatField', [], {}),
            'volume': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'whatcount': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'year': ('django.db.models.fields.FloatField', [], {}),
            'year_pub': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.seagrass': {
            'Meta': {'object_name': 'Seagrass'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'seagrass1': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'seagrass2': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'seagrass3': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'sg_flag': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'source1': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'source2': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'source3': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'year1': ('django.db.models.fields.IntegerField', [], {}),
            'year2': ('django.db.models.fields.IntegerField', [], {}),
            'year3': ('django.db.models.fields.IntegerField', [], {})
        },
        'analysis.shoreline': {
            'Meta': {'object_name': 'Shoreline'},
            'esi': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'esi_field': ('django.db.models.fields.FloatField', [], {}),
            'esi_id': ('django.db.models.fields.FloatField', [], {}),
            'esi_line': ('django.db.models.fields.FloatField', [], {}),
            'esi_line_i': ('django.db.models.fields.FloatField', [], {}),
            'fnode': ('django.db.models.fields.FloatField', [], {}),
            'fnode_1': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'line': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'lpoly': ('django.db.models.fields.FloatField', [], {}),
            'lpoly_1': ('django.db.models.fields.FloatField', [], {}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'rpoly': ('django.db.models.fields.FloatField', [], {}),
            'rpoly_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'source_id': ('django.db.models.fields.FloatField', [], {}),
            'tnode': ('django.db.models.fields.FloatField', [], {}),
            'tnode_1': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.signalequipment': {
            'Meta': {'object_name': 'SignalEquipment'},
            'catfog': ('django.db.models.fields.IntegerField', [], {}),
            'catlit': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'catsit': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'catsiw': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'catspm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colour': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'colpat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'comcha': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'datend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'datsta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'elevat': ('django.db.models.fields.FloatField', [], {}),
            'exclit': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'grup': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'height': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inform': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'light_type': ('django.db.models.fields.IntegerField', [], {}),
            'litchr': ('django.db.models.fields.IntegerField', [], {}),
            'litvis': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'lnam': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'marsys': ('django.db.models.fields.IntegerField', [], {}),
            'mltylt': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'natcon': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ninfom': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'nobjnm': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ntxtds': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'objnam': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'orient': ('django.db.models.fields.FloatField', [], {}),
            'perend': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'persta': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'picrep': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recdat': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'recind': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'ruin': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'rver': ('django.db.models.fields.IntegerField', [], {}),
            'scamax': ('django.db.models.fields.IntegerField', [], {}),
            'scamin': ('django.db.models.fields.IntegerField', [], {}),
            'sectr1': ('django.db.models.fields.FloatField', [], {}),
            'sectr2': ('django.db.models.fields.FloatField', [], {}),
            'sigfrq': ('django.db.models.fields.IntegerField', [], {}),
            'siggen': ('django.db.models.fields.IntegerField', [], {}),
            'siggrp': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'sigper': ('django.db.models.fields.FloatField', [], {}),
            'sigseq': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'sordat': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'sorind': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'topshp': ('django.db.models.fields.IntegerField', [], {}),
            'txtdsc': ('django.db.models.fields.CharField', [], {'max_length': '254', 'null': 'True', 'blank': 'True'}),
            'valmxr': ('django.db.models.fields.FloatField', [], {}),
            'valnmr': ('django.db.models.fields.FloatField', [], {}),
            'veracc': ('django.db.models.fields.FloatField', [], {}),
            'verdat': ('django.db.models.fields.IntegerField', [], {}),
            'verlen': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.snowyplover': {
            'Meta': {'object_name': 'SnowyPlover'},
            'cname': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'org_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'sname': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'spp_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'subunit': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'unit_name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'unit_num': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        'analysis.stateparks': {
            'Meta': {'object_name': 'StateParks'},
            'createdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'creator': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'datasource': ('django.db.models.fields.IntegerField', [], {}),
            'designatio': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'editdate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'editperson': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'full_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'gis_id': ('django.db.models.fields.IntegerField', [], {}),
            'gisacres': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'hub_id': ('django.db.models.fields.IntegerField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'retiredate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'use_type': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'})
        },
        'analysis.stellerhabitats': {
            'Meta': {'object_name': 'StellerHabitats'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '35'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'analysis.sturgeoncoastal': {
            'Meta': {'object_name': 'SturgeonCoastal'},
            'conservati': ('django.db.models.fields.CharField', [], {'max_length': '28'}),
            'exclude': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'specificar': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'sqkm': ('django.db.models.fields.FloatField', [], {}),
            'sqmiles': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.sturgeonestuaries': {
            'Meta': {'object_name': 'SturgeonEstuaries'},
            'area': ('django.db.models.fields.IntegerField', [], {}),
            'cv': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'exclude': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'sqkm': ('django.db.models.fields.FloatField', [], {}),
            'sqmiles': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.substations': {
            'Meta': {'object_name': 'Substations'},
            'geometry': ('django.contrib.gis.db.models.fields.PointField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'owner': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'sta_code': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'analysis.towlanes': {
            'Meta': {'object_name': 'Towlanes'},
            'altitude': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'dateapplic': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'label': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'lat': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'lineclass': ('django.db.models.fields.IntegerField', [], {}),
            'lon': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'longname': ('django.db.models.fields.CharField', [], {'max_length': '17'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '17'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'recnum': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.transmissionlines1993': {
            'Meta': {'object_name': 'TransmissionLines1993'},
            'edit_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'fename': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'fnode': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length': ('django.db.models.fields.FloatField', [], {}),
            'lpoly': ('django.db.models.fields.FloatField', [], {}),
            'miles': ('django.db.models.fields.FloatField', [], {}),
            'orpower': ('django.db.models.fields.FloatField', [], {}),
            'orpower_id': ('django.db.models.fields.FloatField', [], {}),
            'rpoly': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'source': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'tnode': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.transmissionlines2010': {
            'Meta': {'object_name': 'TransmissionLines2010'},
            'code': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'kv': ('django.db.models.fields.FloatField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'owner': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.underseacables': {
            'Meta': {'object_name': 'UnderseaCables'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.urbangrowthboundaries': {
            'Meta': {'object_name': 'UrbanGrowthBoundaries'},
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_le_1': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.viewsheds': {
            'Meta': {'object_name': 'Viewsheds'},
            'area': ('django.db.models.fields.FloatField', [], {}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'inside': ('django.db.models.fields.FloatField', [], {}),
            'major1': ('django.db.models.fields.IntegerField', [], {}),
            'minor1': ('django.db.models.fields.IntegerField', [], {}),
            'perimeter': ('django.db.models.fields.FloatField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'viewshed': ('django.db.models.fields.FloatField', [], {}),
            'viewshed_i': ('django.db.models.fields.FloatField', [], {})
        },
        'analysis.waveenergypermits': {
            'Meta': {'object_name': 'WaveEnergyPermits'},
            'acres': ('django.db.models.fields.FloatField', [], {}),
            'app_date': ('django.db.models.fields.DateField', [], {}),
            'applicant': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'area_miles': ('django.db.models.fields.FloatField', [], {}),
            'company': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'contact': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'geometry': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '99999', 'null': 'True', 'blank': 'True'}),
            'hectares': ('django.db.models.fields.FloatField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'no_devices': ('django.db.models.fields.CharField', [], {'max_length': '75'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'per_miles': ('django.db.models.fields.FloatField', [], {}),
            'permit_no': ('django.db.models.fields.IntegerField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {}),
            'ts': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['analysis']
